### ISSUE TITLE
Missing Gemfile with accurate version restrictions

### ISSUE THREAD

**Issue by jamescrowley** [mroach/RollbarSharp#30]
There's no Gemfile, and the Rake file doesn't work against the latest version of Albacore. I tried adding a Gemspec limiting to v1 but evidently it didn't work against the latest version of v1 either...

Can anyone share what versions of these packages they're actually using to build this? I'm looking to get a NuGet package out rather than just Build from Visual Studio. Thanks!

**Comment by mroach** [comment]
I'm having a poke around the VM I used when developing this. Looks like Albacore 0.3.5. So, that's way out of date. And definitely my bad not using a Gemfile. Since the build process uses Ruby it'll be ideal to create a Gemfile and then I'm sure the Rakefile could do with a rewrite or at least upgraded for Albacore 2.0

**Comment by webcoyote** [comment]
Fixed in 125dcc0
