### ISSUE TITLE
Issue when posting HTML even though [AllowHtml] attribute set

### ISSUE THREAD

**Issue by jamesecwalker** [mroach/RollbarSharp#49]
Hi,

Great tool ... really want to get cracking using it, but have come across an issue:

If the [AllowHtml] attribute is set on a field, and HTML content is posted and an exception is subsequently raised, RollbarSharp ignores the actual exception but shows the standard error you would get as if [AllowHtml] was not set.

**Comment by richardversluis** [comment]
I think this is related to #12, the problem is that RollbarSharp is iterating the `Request.Form` collection which results in the "A potentially dangerous Request.Form value was detected" exception. The only solution is to disable this application wide in the web.config with `validateRequest="false"` which is almost never what you want.

The right solution is to let RollbarSharp use the `Request.Unvalidated.Form` collection, which is available in .NET 4.5. Currently RollbarSharp is 4.0. I have no problems with upgrading to 4.5 considering 4.0 is from 2010, but I don't know how others think about that?

**Comment by jamesecwalker** [comment]
Yeah I thought it may have been related too. We have no problem with the project requiring .NET 4.5 :)
